server:
  port: 8080
  context-path: /acs

  spring..=

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/acs?characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false
